name: 'S3 Upload Action'
description: 'upload an artifact to s3'
author: 'bsdlp'
inputs: 
  s3_bucket:
    description: 's3 bucket name'
  s3_key:
    description: 'the destination path in s3'
  file:
    description: 'path to file to upload to s3'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.s3_bucket }}
    - ${{ inputs.s3_key }}
